"""Translate synthesized SERV connectivity into a small C++ gate simulator."""

import json
from collections import Counter, deque
from pathlib import Path

from jev import GATES


def translate(source: Path, destination: Path):
    module = json.loads(source.read_text())["modules"]["serv_rf_top"]
    ports = module["ports"]
    clock = ports["clk"]["bits"][0]
    # Nets 0 and 1 are constants. Unspecified startup/don't-care values become 0.
    def net(bit):
        if isinstance(bit, int):
            return bit + 2
        if bit not in ("0", "1", "x", "z"):
            raise ValueError(f"Unknown net bit {bit!r}")
        return int(bit == "1")

    driven = {0, 1}
    for port in ports.values():
        if port["direction"] == "input":
            driven.update(net(b) for b in port["bits"])

    gates = []
    flops = []
    for name, cell in module["cells"].items():
        kind = cell["type"]
        if kind == "$scopeinfo":
            continue
        wires = cell["connections"]
        if any(len(bits) != 1 for bits in wires.values()):
            raise ValueError(f"Cell {name} is not bit-level: {kind}")
        if kind == "$_DFF_P_":
            if wires["C"] != [clock]:
                raise ValueError(f"Unsupported clock on {name}")
            d, q = net(wires["D"][0]), net(wires["Q"][0])
            if q in driven:
                raise ValueError(f"Multiple drivers for net {q}")
            driven.add(q)
            flops.append((d, q))
        else:
            gate = kind.removeprefix("$_").removesuffix("_")
            if gate not in GATES or kind != f"$_{gate}_":
                raise ValueError(f"Unsupported synthesized cell {name}: {kind}")
            inputs = [net(wires[p][0]) for p in GATES[gate][1]]
            gates.append((gate, inputs, net(wires["Y"][0])))

    # Topologically order combinational gates, rejecting loops and floating nets.
    producers = {}
    for index, (_, _, output) in enumerate(gates):
        if output in driven or output in producers:
            raise ValueError(f"Multiple drivers for net {output}")
        producers[output] = index
    pending = []
    consumers = [[] for _ in gates]
    for index, (_, inputs, _) in enumerate(gates):
        dependencies = set()
        for bit in inputs:
            if bit in producers:
                dependencies.add(producers[bit])
            elif bit not in driven:
                raise ValueError(f"Undriven gate input {bit}")
        pending.append(len(dependencies))
        for dependency in dependencies:
            consumers[dependency].append(index)
    ready = deque(i for i, count in enumerate(pending) if not count)
    ordered = []
    levels = {bit: 0 for bit in driven}
    gate_levels = []
    while ready:
        index = ready.popleft()
        _, inputs, output = gates[index]
        level = 1 + max(levels[bit] for bit in inputs)
        levels[output] = level
        gate_levels.append(level)
        ordered.append(gates[index])
        for dependent in consumers[index]:
            pending[dependent] -= 1
            if not pending[dependent]:
                ready.append(dependent)
    if len(ordered) != len(gates):
        raise ValueError("Combinational loop in netlist")
    available = driven | producers.keys()
    for bit in [d for d, _ in flops] + [net(b) for p in ports.values() if p["direction"] == "output" for b in p["bits"]]:
        if bit not in available:
            raise ValueError(f"Undriven output or flip-flop input {bit}")

    initial = {}
    for wire in module["netnames"].values():
        init = wire.get("attributes", {}).get("init")
        if init is not None:
            for bit, value in zip(wire["bits"], reversed(init)):
                if value in "01" and isinstance(bit, int):
                    bit = net(bit)
                    if bit in initial and initial[bit] != int(value):
                        raise ValueError(f"Conflicting initialization of net {bit}")
                    initial[bit] = int(value)

    lines = [
        "// Generated by netlist.py. Connectivity only; gate answers are loaded at runtime.",
        "#pragma once", "#include <array>", "#include <cstdint>",
        "struct Gate { uint32_t op, arity, a, b, s, y, level; };",
        "struct Flop { uint32_t d, q; };",
        f"constexpr unsigned NET_COUNT = {max(available) + 1};",
        f"constexpr std::array<Gate, {len(ordered)}> GATES = {{{{",
    ]
    counts = Counter()
    for (gate, inputs, output), level in sorted(zip(ordered, gate_levels), key=lambda item: item[1]):
        counts[gate] += 1
        padded = inputs + [0] * (3 - len(inputs))
        fields = [list(GATES).index(gate), len(inputs), *padded, output, level]
        lines.append("    {" + ",".join(map(str, fields)) + "},")
    lines += ["}};", f"constexpr std::array<Flop, {len(flops)}> FLOPS = {{{{"]
    lines += [f"    {{{d},{q}}}," for d, q in flops]
    lines += ["}};", f"constexpr std::array<Flop, {len(initial)}> INITIAL = {{{{"]
    lines += [f"    {{{value},{bit}}}," for bit, value in sorted(initial.items())]
    lines.append("}};")
    for name, port in ports.items():
        if not name.isidentifier():
            raise ValueError(f"Invalid port name {name}")
        bits = ",".join(str(net(bit)) for bit in port["bits"])
        lines.append(f"constexpr std::array<unsigned, {len(port['bits'])}> {name} = {{{{{bits}}}}};")
    for name, signal in {
        "trace_count_high": "cpu.state.o_cnt",
        "trace_count_ring": "cpu.state.cnt_r",
        "trace_rs1": "cpu.i_rdata0",
        "trace_rd": "cpu.o_wdata0",
    }.items():
        bits = module["netnames"][signal]["bits"]
        if any(net(bit) not in available for bit in bits):
            raise ValueError(f"Trace signal was removed during synthesis: {signal}")
        lines.append(f"constexpr std::array<unsigned, {len(bits)}> {name} = {{{{{','.join(str(net(b)) for b in bits)}}}}};")
    destination.write_text("\n".join(lines) + "\n")
    return {"gates": len(ordered), "levels": max(gate_levels), "flip_flops": len(flops), "gate_types": dict(counts), "nets": max(available) + 1}
